name: cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: portfolio-deploy-session
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Check if dist exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi

      - name: Deploy to S3
        run: |
          aws s3 sync dist ${{ secrets.AWS_S3_BUCKET }} --delete
